### ISSUE TITLE
import only needed part of lodash

### ISSUE THREAD

**Issue by phra** [ramiel/mongoose-aliasfield#10]
hi,

atm you are importing all lodash bundle to just use two functions (and one is "isUndefined" that can be safely substituted by "=== void 0" or "=== undefined".

this should be avoided because it's a library and not an application.

**Comment by ramiel** [comment]
You're right. I think this can be easily fixed.If you want to contribute with a PR you're welcome.

**Comment by ramiel** [comment]
You're right. I think this can be easily fixed.If you want to contribute with a PR you're welcome.

**Comment by ramiel** [comment]
In case, please make the PR against the `develop` branch

**Comment by phra** [comment]
done #11 
btw there is a unit tests that is failing that is not related to my changes. (it was already failing..)
can you have a look and fix it?
thanks.

**Comment by phra** [comment]
sorry didn't see the previous message.
i've open another pr targeting develop branch. #12

**Comment by ramiel** [comment]
Thank you for the contribution! Looks like the test are not passing for a mongoose version greater than 4.7.5. This already happened in another repository (looks like they put breaking changes in a minor version). I'll try to solve it before merging your PR. Thank you again

**Comment by ramiel** [comment]
Ok, I've found the problem. Starting from mongoose >=4.9.8 it is not possible to have three or more dots in the virtual name. I filled a [bug](https://github.com/Automattic/mongoose/issues/5250) to mongoose. I fixed the tests and included a version of the code which get rid of lodash completely, so I'll close your PR and I'll make a new release shortly (0.3.4). Thank you again.

**Comment by phra** [comment]
why you didn't merge before make changes? i won't have any contribution back in this way. that's not fair..
