### ISSUE TITLE
model.save() saved  req.body in toString format having special characters in each key 

### ISSUE THREAD

**Issue by rockamitk** [ramiel/mongoose-aliasfield#13]
//Schema Def
`const schema = new mongoose.Schema({
  name: {type: String, alias:'enquiry_name', required: true, minLength: 3, maxLength: 30},
  email: {type: String, alias:'enquiry_email', required: true},
});
schema.plugin(require('mongoose-aliasfield'));
`

//Model Def
User = module.exports = mongoose.model('User' ,schema);

let user = new User({
 enquiry_name: req.body.enquiry_name,
 enquiry_email: req.body.enquiry_email
});
user.save()

/*Stores in Db*/
{ "_id" : ObjectId("5a0d70418caef3234092fd2e"), "name" : "{ name: 'raj',\n  email: '{ email: \\'raj@aviota.ai\\',_id: 5a0d70418caef3234092fd2e,}\\',\\n  _id: 5a0d70418caef3234092fd2e}',"email" : "{ email: 'raj@aviota.ai',\\n  _id: 5a0d70418caef3234092fd2e,\\n}',\n  _id: 5a0d70418caef3234092fd2e}"}

What actually happening here??

**Comment by ramiel** [comment]
It looks like `req.body.enquiry_name` contains an object instead of a string.    
Try to write
```
let user = new User({
enquiry_name: 'a name',
enquiry_email: 'an@email.com'
});
user.save()
```

and see what happens

**Comment by rockamitk** [comment]
No, req.body's key has only string, that what i am sending from client.
After new model initialization, the key has been storing object.

Is there any version issue ? because I am using 
 "mongoose": "^4.10.6",
 "mongoose-aliasfield": "^0.3.7",
  "express": "^4.16.2",

**Comment by rockamitk** [comment]
It was mongoose version issues. I was using mongoose 4.10.6.

Is there any create alias of _id?

**Comment by ramiel** [comment]
I never tried honestly, but `_id` is already aliased by mongoose as `id`, maybe it's enough.
