### ISSUE TITLE
Alias field on population

### ISSUE THREAD

**Issue by bendpx** [ramiel/mongoose-aliasfield#4]
Hey,
I have a scehma:

var AccountSchema = new Schema({
    name: {
        type: String,
        required: true,
        alias: 'label'
    },
    children: [{type: ObjectId, ref: 'Account'}],
});

And I want to query it and populate by the alias (for the children as wel), and I do it like that:
Account.findOne({name: 'root'}, 'label children -_id' ,function (err, acc) {
    Account.populate(account, {path: 'children', select: 'label children -_id'}).then(function() {
       console.log(acc.toAliasedFieldsObject()); 
    });
});

The problem is the alias is only valid on the parent and not on the children. can I alias the populated document's fields?

Thanks!

**Comment by ramiel** [comment]
I will soon investigate about this. Thank you for reporting

**Comment by ramiel** [comment]
Ok, I made some tests. Properties are aliased for parent and for children. Even the properties representing the children can be aliased. When you call toAliasedFieldObject in parent this makes nothing on children for which you have to explicitly call (it's a different model after all. Maybe we could think to an option to apply it recursively).
You can find an example of working code in test (in master). Anyway here there is a little code

```javascript
var PersonSchema = new Schema({
    'n' : {'type' : String, 'required' : true, alias: 'name'},
    'c' : {'type': Schema.Types.ObjectId, ref: 'person', alias: 'child' }
    
});
PersonSchema.plugin(fieldsAliasPlugin);
var Person = mongoose.model('person', PersonSchema);

var children = new Person({name: 'Tim'}),
    parent = null;

children.save(function(err){
    if(err) return done(err);
    parent = new Person({name: 'Mike', child: children._id });
    parent.save(function(err){
        if(err) return done(err);

        this.Person
                .findOne({n: 'Mike'})
                .populate('c')
                .exec(function(err, person){
                    if(err) return done(err);
                    // Every model has toAliasedFieldsObject
                    assert.isFunction(person.toAliasedFieldsObject);
                    assert.isFunction(person.child.toAliasedFieldsObject);

                    // Parent and child properties are aliased
                    assert.equal(person.name, 'Mike');
                    assert.equal(person.child.name, 'Tim');

                    // You can call toAliasedFieldsObject on the children
                    var t = this.found_parent.child.toAliasedFieldsObject();
                    assert.equal(t.name, 'Tim');

                }.bind(this));


    });
}.bind(this));
```

Do this solve your doubts?
