### ISSUE TITLE
Can the method toAliasedFieldsObject() be extended to an array of docs as well?

### ISSUE THREAD

**Issue by codebysrini** [ramiel/mongoose-aliasfield#5]
Hi 
I have tried applying your method toAliasedFieldsObject() to an array of objects but it didnt work. Hence i had to loop through the individual documents and then apply the method to each document. model.find() query returns more than one document in many cases as opposed to your example. Is it possible for you to make this method work for an array of docs as well ? that would be really helpful.
Thanks!

**Comment by ramiel** [comment]
Hi,
my solution to this would be to apply a map to the array just like you could do

```javascript
model.find({},function(err, results){
   results = results.map(function(r){return r.toAliasedFieldsObject();});
});
```

What I have to understand is if it's better to put this generalization on the plugin itself or to let the user call a map function. The fact is that the user always know is he has an array or an object while the plugin has to check which adds a little bit of overhead.
Anyway your issue let me discover I have an error in the readme ;)

I'll let you know what I'll decide.

**Comment by ramiel** [comment]
Ok, sorry. I definitely cannot apply this modification because the array of results simply have not the `toAliasedFieldsObject` method. This method is only present on the model instance itself so the map function is the only viable solution. I don't want to modify the prototype of the Array object of course.
Sorry for this!

**Comment by codebysrini** [comment]
That works !! Thanks for your input
