### ISSUE TITLE
How to use with Update/Remove/etc.

### ISSUE THREAD

**Issue by Nepoxx** [ramiel/mongoose-aliasfield#6]
It would be nice to have a static that can convert a "long name" object to the short version, for Update queries.

``` javascript
var longNames = {
    'timestamp' : new Date(),
    'name'      : 'Jhon',
    'surname'   : 'Doe',
    'profile.address': 'Rue de Morgane',
    'profile.phone_number': '051-123456 78',
};

Person.toShort(longNames);
/*
{
  t: 1467750986208,
  n: 'Jhon', (this is a typo in your doc by the way =] )
  s: 'Doe',
  ...
}
*/
```

The issue I'm having without this is with non `New Model()` queries, such as updates, findByIdAndUpdate, etc. Right now I can't do something like this:

``` javascript
var updateFields = { // This might be part of a query a client is sending me, for instance.
  surname: 'Smith' // and might have extra attributes
}
Person.update({name: 'Jhon'}, updateFields).exec();
```

The alternative is to do this, which is not pretty and defeats the purpose of having a library handle aliases:

``` javascript
function updatePerson(dataFromFrontend) {
 var updateQuery = {};
 if(dataFromFrontend && dataFromFrontend.name)
  updateQuery.n = dataFromFrontend.name;
 if(dataFromFrontend && dataFromFrontend.surname)
  updateQuery.s = dataFromFrontend.surname;
 //etc.
}
Person.update({n: 'Jhon'}, updateFields).exec();
```

Thoughts?

**Comment by ramiel** [comment]
I'll add a test to verify this because I was pretty sure it should already do the conversion automatically (but maybe I'm not remembering well, it's a long time ;) ).
Can you send me the mongoose version?

**Comment by Nepoxx** [comment]
Mongoose 4.4.4 and mongoose-aliasfield 0.0.5

What you're saying is that we can already use aliases for update queries and such? I'll try it out.

**Comment by ramiel** [comment]
Yes, I checked and no, there is no support for object transformation during any query. I'll think to a solution (which for now looks what you suggested, a static method). I'll give you some updates as soon as I have something

**Comment by Nepoxx** [comment]
Maybe we should open an issue on Mongoose's repo to support query middleware? I feel like that would be a very useful feature to have!

Merci ;)

**Comment by ramiel** [comment]
They exists actually :D 
http://mongoosejs.com/docs/middleware.html

**Comment by ramiel** [comment]
I was trying to understand if I could use the `update` hook. During the update and before the hook is called, the update_doc passed (the second parameter) is checked and casted to something valid. So every aliased field is stripped away. So probably I cannot use these hooks and should fallback ona static function as you suggested. I would have preferred to rely on something automatic...
I will open a mongoose issue to see if there is something else to do

**Comment by Nepoxx** [comment]
That's my understanding as well, short of monkey patching it in before the update document is modified, I don't see a clean way of doing it. Please link the related issue here :)

**Comment by ramiel** [comment]
Of course Automattic/mongoose#4306

**Comment by ramiel** [comment]
Please, have a look at the branch [feature/fromAliasedObject](https://github.com/ramiel/mongoose-aliasfield/tree/feature/fromAliasedObject).
You'll find a solution I'm totally not satisfied of. Should work by the way. On readme is explained how it works and you could look at the added tests too.
Let me know.
Ps, any suggestion or PR is welcome :)
